let
    Source = Table.Combine({#"EmpMaster-DohaHQ", #"EmpMaster-Wakra", #"EmpMaster-AlKhor"}),
    #"Changed Type with Locale" = Table.TransformColumnTypes(Source, {{"HireDate", type date}}, "en-US"),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type with Locale", each true),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered Rows", "Allowances", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"Allowances.1", "Allowances.2"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Allowances.1", type text}, {"Allowances.2", type text}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Changed Type", "Allowances.1", Splitter.SplitTextByDelimiter(":", QuoteStyle.Csv), {"Allowances.1.1", "Allowances.1.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Allowances.1.1", type text}, {"Allowances.1.2", Int64.Type}}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Changed Type1", "Allowances.2", Splitter.SplitTextByDelimiter(":", QuoteStyle.Csv), {"Allowances.2.1", "Allowances.2.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Allowances.2.1", type text}, {"Allowances.2.2", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Allowances.1.2", "Housing"}, {"Allowances.2.2", "Transport"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Allowances.1.1", "Allowances.2.1"}),
    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Removed Columns", {{"DateOfBirth", type text}, {"HireDate", type text}, {"MonthlyBasicSalaryQAR", type text}, {"Housing", type text}, {"Transport", type text}}, "en-US"),{{"EmployeeID", Text.Trim, type text}, {"FullName", Text.Trim, type text}, {"Gender", Text.Trim, type text}, {"DateOfBirth", Text.Trim, type text}, {"Nationality", Text.Trim, type text}, {"MaritalStatus", Text.Trim, type text}, {"HireDate", Text.Trim, type text}, {"DeptID", Text.Trim, type text}, {"JobID", Text.Trim, type text}, {"LocationID", Text.Trim, type text}, {"Grade", Text.Trim, type text}, {"EmploymentType", Text.Trim, type text}, {"MonthlyBasicSalaryQAR", Text.Trim, type text}, {"Housing", Text.Trim, type text}, {"Transport", Text.Trim, type text}, {"Email", Text.Trim, type text}, {"MobileNo", Text.Trim, type text}, {"Status", Text.Trim, type text}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Trimmed Text",{{"Nationality", Text.Proper, type text}, {"FullName", Text.Proper, type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Capitalized Each Word", each true),
    #"Capitalized Each Word1" = Table.TransformColumns(#"Filtered Rows1",{{"Gender", Text.Proper, type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Capitalized Each Word1", each true),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows2","F","Female",Replacer.ReplaceValue,{"Gender"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","M","Male",Replacer.ReplaceValue,{"Gender"}),
    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Replaced Value1", {{"DateOfBirth", type date}}, "en-US"),
    #"Inserted Age" = Table.AddColumn(#"Changed Type with Locale1", "Age", each Date.From(DateTime.LocalNow()) - [DateOfBirth], type duration),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Age",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "Nationality", "MaritalStatus", "HireDate", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "MobileNo", "Status"}),
    #"Calculated Total Years" = Table.TransformColumns(#"Reordered Columns",{{"Age", each Duration.TotalDays(_) / 365, type number}}),
    #"Rounded Off" = Table.TransformColumns(#"Calculated Total Years",{{"Age", each Number.Round(_, 2), type number}}),
    #"Added Conditional Column" = Table.AddColumn(#"Rounded Off", "AgeBand", each if [Age] < 25 then "Under 25" else if [Age] < 35 then "25-34" else if [Age] < 45 then "35-44" else if [Age] < 55 then "45-54" else if [Age] < 65 then "55-64" else "Over 65"),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Conditional Column",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "MobileNo", "Status"}),
    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Reordered Columns1", {{"HireDate", type date}}, "en-US"),
    #"Inserted Age1" = Table.AddColumn(#"Changed Type with Locale2", "Age.1", each Date.From(DateTime.LocalNow()) - [HireDate], type duration),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Age1",{{"Age.1", "ServiceYrs"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "ServiceYrs", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "MobileNo", "Status"}),
    #"Calculated Total Years1" = Table.TransformColumns(#"Reordered Columns2",{{"ServiceYrs", each Duration.TotalDays(_) / 365, type number}}),
    #"Rounded Off1" = Table.TransformColumns(#"Calculated Total Years1",{{"ServiceYrs", each Number.Round(_, 2), type number}}),
    #"Added Conditional Column1" = Table.AddColumn(#"Rounded Off1", "TenureBand", each if [ServiceYrs] < 1 then "Under 1Yr" else if [ServiceYrs] < 4 then "1-3Yrs" else if [ServiceYrs] < 11 then "4-10Yrs" else if [ServiceYrs] < 21 then "11-20Yrs" else "Over 20Yrs"),
    #"Reordered Columns3" = Table.ReorderColumns(#"Added Conditional Column1",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "ServiceYrs", "TenureBand", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "MobileNo", "Status"}),
    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns3", {"EmployeeID"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Duplicates",{{"MonthlyBasicSalaryQAR", Int64.Type}, {"Housing", Int64.Type}, {"Transport", Int64.Type}}),
    #"Inserted Sum" = Table.AddColumn(#"Changed Type3", "Addition", each List.Sum({[MonthlyBasicSalaryQAR], [Housing], [Transport]}), Int64.Type),
    #"Reordered Columns4" = Table.ReorderColumns(#"Inserted Sum",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "ServiceYrs", "TenureBand", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "Addition", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "MobileNo", "Status"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns4",{{"Addition", "TotalSalary"}}),
    #"Added Conditional Column2" = Table.AddColumn(#"Renamed Columns2", "HasEmail", each if [Email] <> null and Text.Trim([Email]) <> "" then "Yes" else "No"),
    #"Reordered Columns5" = Table.ReorderColumns(#"Added Conditional Column2",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "ServiceYrs", "TenureBand", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "TotalSalary", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "HasEmail", "MobileNo", "Status"}),
    #"Added Conditional Column3" = Table.AddColumn(#"Reordered Columns5", "HasContactInfo", each if [MobileNo] <> null then "Yes" else "No"),
    #"Reordered Columns6" = Table.ReorderColumns(#"Added Conditional Column3",{"EmployeeID", "FullName", "Gender", "DateOfBirth", "Age", "AgeBand", "Nationality", "MaritalStatus", "HireDate", "ServiceYrs", "TenureBand", "DeptID", "JobID", "LocationID", "Grade", "EmploymentType", "TotalSalary", "MonthlyBasicSalaryQAR", "Housing", "Transport", "Email", "HasEmail", "MobileNo", "HasContactInfo", "Status"}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Reordered Columns6", "Text Before Delimiter", each Text.BeforeDelimiter([FullName], " "), type text),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "FirstName-ColfromEx"}})
in
    #"Renamed Columns3"